package com.cssm.desktop.ui.components

/** 国旗 PNG base64 内嵌（第 1 部分，来源 flagcdn.com） */
internal val FLAG_IMAGE_PART1: Map<String, String> = mapOf(
    "ae" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoBAMAAACbTmAyAAAAElBMVEUAAAAAhD3////IEC6r1r+qqqqRmeBQAAAALUlEQVQ4y2MwhgNBvIBhVOFIVOiCFyApVMILRhUOJ4WheAGSQgb8YFThiFEIAL/lq1Xv0RoWAAAAAElFTkSuQmCC",
    "ar" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAyCAMAAAD886zOAAAATlBMVEX////r0av9/PzpzKHs1bby5tnoyJR0rN+jyOqiyOrt28XkwYnNiRfalhblnwnfuYXjuXPdsGbWpmTQlkD59fXbql7r18DXoErvrAz2tA6P72NOAAAAvElEQVRIx+2Viw3DIAwFMTZuy5+QQNh/" +
        "0TbtCpaiSr4BTn56NpiHMEaFKlShCv9U+BLG3IJ1w/vhrJRvJwAERtqF5mPgUlsAYBGjBajt6P1olUgitWMsPaYUZ0V2AkLisMVzrTNugUliwlFKyh/SVshJrAyVmVbOK/UyRCKPK3LOV2QkmVK2eZXSG4mUYoDqcfT5WRsvsjZmD4ih1cCDhY7PEjIhgNTpfZv2zrt7" +
        "XibzFEZ/PRWqUIUq/PEGSu1SsRKhYjsAAAAASUVORK5CYII=",
    "at" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1AgMAAACrRoTXAAAACVBMVEXIEC7////bYHQgqVWYAAAAH0lEQVQ4y2NgGAW0B6uwAIZQLGBUkMqCWEN+FNAeAAA7xIt1Gd2jZQAAAABJRU5ErkJggg==",
    "au" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAMAAABevo0zAAAAXVBMVEXkACvv8fZ+jrMIKG4OLHFBWY9Va5sBIWn////rQGD4v8ntvMkqRYGAkLR2h64zTYdKYZX3+Pujr8keO3rX2+e7w9fwcIiPnb0CImrr5exgdKGWo8H6z9erts7yzddHEiheAAABrklEQVRIx+2V" +
        "yZKEIBBEQVASGwH3trf//8w5uAu2xAzHqYMRlvCiCrJSInOAJlzMkYEQQpAtCZ7cJJG5CAwiicwBqrkfyPVtXBEMTKYNc5U7IF+/BgMFL3bIDXDFFdy39373AsUeuQCvcEKk6Qlwh3yMwMcljlVtWzEXmI5hq08nuxdQjsBheqvstMBt+An0btMEThBCPFlnp9KAVi4w" +
        "NNye66SoRUwgE4JFBZ7oMDrw15eyFST3yaYEXp3shhE4vX3OZbO6R//uC0fYFMglkbdV2HPmKGx34CrgcRi9BbcbPR+ScZvy/eXaFuVbbc1hgzuYgwfZDkN7qNDoTYYU5bRJ++xLz0g9H1gFHCe4FpuaybY6n8HOVc4DZ8syVd9ks8d5fwEUyOVSjrX1d4P9WxgTF6go" +
        "VXErfD4jtxx0hkpFBhZJRGCaMdE0gmVpJCBr6BuoaMNitZyO9meinSFvAKDhkYAsoWOFVF/3zNgl8K503wJA2+urppnKrGIBsjEoS4Qo8UlpH6LDDNZuzOZ8jBugMQFAnQmR6WsgM8NgQlqul8f3uNfG1PH98B8oxA8n5FdQBY0ijQAAAABJRU5ErkJggg==",
    "be" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAABFBAMAAAAvJHy2AAAAD1BMVEUAAADvM0D92iXzazZVSgz2L4TiAAAAK0lEQVRIx+3KMREAIAwEsLdQC+AE/6JYX0MvmZO0d8qdFlEURVEURVFcFj+GqMTD+NqXTQAAAABJRU5ErkJggg==",
    "br" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA4CAMAAABdaI+oAAAAw1BMVEUAlED/ywAwJoEHlj4SmDs3LHv7yAKnuBZYpypCoi5trCXtyATixQYgmjf9ygG8lSk2LYT0xwQyKIE+NIdNPW5MRJGKsh25uxHHvg4vnjPWwgpmX6JFN3OsiDNgTWJeV5y74syKbUjYrBh8da5V" +
        "RGmdu7vX7OGopsql2rzJnyGMhre0tdDI59aZtRp6riKVkL2V0rBWUJj4/PpaUpq018h5fKppwI7Q3d7Mx8CNpa58iqulycCjkISAdpbVrS9uaKTPuH6BIXwtAAACKElEQVRYw+1XaXOiQBDNtGJAUUaORMUDRQHFRI3mzm72//+qpYZhist1RKitVPm+WGrXq+7pN697" +
        "bm6uuCJCrVYunyTLUol09VsU4LZeFp/YQgQtsRS69j1iuG9fztfsohi6zQvp+j2UQq9/iVbuOiiDzl1hBUkDwtBYTse6IOjj6bJBfhgUU1D9IaQbDYFhOAopHwooSJRJfYoOCegKOQVZLCRlhBQBUhCU8J/zZN6kUlYgB5Sxxa+gdqSVmZBHKMxou3t8Mq89NihfYw65" +
        "mLOARw4F9QdMcSM4ghELGfTPkHL3fbE4bA+fi/fNs4njhMMur8wlOXYl/ljW1vLWznb99PLkLD522M2mGChIOqkVii/b3BsYG3vT/nBf15538E1KOE0EHlNQZHsRxuDGyjRdxwvynJAv42RkrlHGbS/EMN0L03deLEKpp2OzRpm0PYKMCCeq4QeHGuQtZIIzRvkPwlWc" +
        "dOdvnU+Dg/BUyapKP8FeW9av0yXnNgUwaFG5E8ZtvHpvHE3JyKYzBdhQPtWIV47dNy7ZpIW9NOygwlV4RzRGt9Iw/OYTdurqdeYxpugMg+K1/fycCRMzB+KGz0BStG1W8CZyRB5zSNhXmCL4lEkzQd1puw2wBLns67jBYgzfGGvMYFGvfeEI0FYwMYuMgLwhRZtiGMWG" +
        "FBujaJYeo2G9svj/B335q0gFy1L561wFC2cFK3H5S3sFz4ryHz4VPM2u+NH4C4s2LLeHO8TWAAAAAElFTkSuQmCC",
    "ca" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAMAAABevo0zAAAAQlBMVEX/AAD/R0f/Y2P/29v/6Oj/Cgr/VFT/////Gxv/cnL/h4f/lZX/7+//srL/oKD/XFz/zs7/ycn/NTX/eXn/+Pj/u7s/V1YHAAABDUlEQVRIx+WWy3LDIAxFL0/xsgHb+f9f7aLO0KR2xgEt0qlW" +
        "wNWcAWkkBBwYXTRctT8JVIoZmDMvUAGKFZiBzAXUmkgBgPpeDwOT8ckCQE4eiePJrgmOJYa2CZYFGJoQWIBTE27DwBqIdBMSUai9QB8LkUX8kRVHFGGJSvQdQAmYBcBM4n4uaAawGEB2AG/33dyA8TGYb8bQnDuYrqTIcwf5CUDlXnk49f4Np1cxnHqeXE7v6Epfpejl" +
        "WF50b+lt9ki120Ath99iGOs2z6nZ0zHQvvyj5If74VOq3Siwwgk/121dtzp74VAGgXr/52Lc/0DNNIqEwDzbrCsz0HtmoJTMQGuZgUL8uxn7MvAL2t0iyxNQ808AAAAASUVORK5CYII=",
    "ch" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAABQAgMAAADzfxo+AAAADFBMVEX/AAD/////gID/wMCov4oYAAAANklEQVQ4y2NgGAWUgqmhoWGjgrQTZFoFBFdDQ8NBdANUkDEUCTiMCmIXxBp0owmMXoKjgFQAAH/3gHGvQgbmAAAAAElFTkSuQmCC",
    "cl" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1BAMAAAAkBnF3AAAALVBMVEUAMqD////aKRzsk41Wd8BtLV3V3e+dsNs8YrcZRqnEz+n19/zu8flvi8mYT21aZe5QAAAAcklEQVRIx2NgQAaOgjgBw0hWyE6swh5iFRY2EKnwYAExCnnTlgnuWraCCBO9gQyxCUQo5FwoKHiB" +
        "KDc2CsoQ55lCacEGohTudigsIEYhSyYDSwIxCjmAeOZoCqdIYSgyeGyMEzAoEQlGFY4qHFU4ghUCAOlD1cGIdtceAAAAAElFTkSuQmCC",
    "cn" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1CAMAAADh9px2AAAANlBMVEXuHCX//wDwLyHyVBvuIiP5qw3xPx71dRX+5wP3jRL4mRD/9gHzXxnySxz7wQn6tgv7ygj80QdOKUmjAAAAwElEQVQYGe3BSXLDMAwEwBkQBFct+f9nbSVOpORIwYdUsRv/msKTmBS42lvEbYZT" +
        "ZKuKe2TFDytrwl2JgpME3LUy4TcxKIYpueKPHAsGaDgUsoXDghepjQtG9MbTh+FFLcaqGCE7v1VcFMUYReGnHHClGLfxkOBFGw8RXjqZK9kUV0EwKnJTWGbHSUKsQTBEc8KTxoiLQhaMMcOXjgvL2eBpEQlws8CTpFThKnLvcCSZ2wJHoj3BmWCapmmapumtHrOgA8RD" +
        "dxj4AAAAAElFTkSuQmCC",
    "co" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1BAMAAAAkBnF3AAAAD1BMVEUAMIfIEC7/zQB/fkQyKHC6sEclAAAAKUlEQVRIx2NQIhIwjCocVTiqcAQrNCYSMIyCkQNciAQMgkSCUYUjRyEA3Ey/QYscrhkAAAAASUVORK5CYII=",
    "cz" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1CAMAAADh9px2AAAAP1BMVEXXFBpMc579/f7m6/G+GSYcToQaQnkRRX7////rio2LJkA+OWfZ4euOqMJMNl+pvNF5K0nVFBubsclPYoxfgqgnqyWVAAAA50lEQVRYw63OBxaCMBBF0TEQxoIV979Wgw3EkEz5bwH3PLo3W2jE" +
        "8QwGmaGTIwidfILMmwYM4iY/IGxyAkGTMxAz+QOmyYAFAZNLkOMtYEHvZAb0TeZA12QedEyugGmyB4McjwELGidLoGmyCFomK6B+sgaqJ+ugclIAMg89GGSWTwpBHnbChODlStIk3KElAoKdYk8CqvbqoHKvCmr3KqB+rwwa9kqgaa8A2vZWwW5PhATNe3nQsZcFPXsZ" +
        "0Lf3Dzr3lqB7bwGeWkKCiL05CNmbQNDeF0TtvUHc3gsE7o0gdC+F3SN6AJC2ULEpR+kgAAAAAElFTkSuQmCC",
    "de" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAwAgMAAAD7ixVkAAAACVBMVEUAAADdAAD/zgDGIigcAAAAG0lEQVQoz2NgGAVUBaFYwKgg+YKrsIBRQbIFAbpUPtBQ8ZOVAAAAAElFTkSuQmCC",
)
