package com.cssm.desktop.ui.components

/** 国旗 PNG base64 内嵌（第 2 部分，来源 flagcdn.com） */
internal val FLAG_IMAGE_PART2: Map<String, String> = mapOf(
    "dk" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA9BAMAAADIVfMaAAAAFVBMVEXIEC7////xxMvLHTnpnqr//v766Opz5UdkAAAAOklEQVRIx2NgQALMgkDgwEAYjCocVTiqcIQpVEIGIIVJSlgBgyBxQHSEKiQ6HEfT46jCUYWjCgkqBACPZDi5z2Vb2gAAAABJRU5ErkJggg==",
    "ee" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAzAgMAAAB9H2fKAAAACVBMVEX///8Acs4AAABr0YPHAAAAHElEQVQ4y2MIxQIYRgWpK7gKCxgVpLLgKKA9AAATq1K8225QYQAAAABJRU5ErkJggg==",
    "es" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1CAMAAADh9px2AAAA3lBMVEX6vQCtFRnnkwabMRKZPA30tQH4uwGXKhDuswC+OxmrqKnjqQOuAyOcSQZ6bh+2TQ6bXAjFlwrvrQTSpyHnnQWzpXigIBCqoY5EZHlqbkeKVBK6ZCKHLxKoggWrWl/Sr0qUFBe8jKamiSDTnhKf" +
        "UzLjsh/OWwo8MHOrcA6sKxiRdAmyXUfSZauEf1KvjHjccwvLhg+1rZixCiCjFB9BWGODIA7Zggeynaf5vwtvf2zJfwarbly2GxyyiwSuREt5G02qMkCjgCmvl4dxRwB7XgClO0cQP5Wpdl68fpO9fp8nzyHlAAABfklEQVRYw+3Wx26DQBAG4MVb6RhMM8Vg494r7o5b" +
        "yvu/UC5RTrktUpSI/7aXTzPSzGqAUHBACZZgCf4PsFJwwF9OtVBtyyxNbm+L4nDLauFIlq2WXFC300BfXBUxmFZJIWBPWTiC03ccRS+maxktIUWUOmjPj5m6iIFsDAbGQDNmANT2JifY6+HKxkAhzXpXyyKzqMUHsijCupKslaEkTdwbO0W8A2nbRFfu92T4no5SlzXs" +
        "Np9H5jbRk8djPcxHo9xlDYkT3JxfxL6iackwl0apKwh9EXMtyTF+24jrgZZ0L+lH6naCuN/hqlC8HTr6Mgy7q1Us5W5NlPgqBDhWpnVKw+7q1TFUVFs8+caGiOcJqUMIl90LRQiyRnyscYmduU3qEEIEVUNTEWtIAeYemy9QrSNkco+N3Gwyg0KIMlWAKsKnJuemjH2/" +
        "aYYUoskTITizfM3nA33PGwM5yMa73SGrgKrnedyfLAEAYGYy/P36zRR+OZTnXAmWYAn+lE9C+ywNWkwjFAAAAABJRU5ErkJggg==",
    "fi" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAxBAMAAAC/lzNhAAAAD1BMVEUAL2z///+/yto4XIxviqwRGMjzAAAAMklEQVQ4y2MQRAADBhBgEcQKGEYVjiocTAqVEACqUAkrYBgFowADEJ16RnPhqMKhqBAAZ9pal1I6oX4AAAAASUVORK5CYII=",
    "fr" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1BAMAAAAkBnF3AAAAD1BMVEX///8AJlTOESbeYG5Wb42QNrxKAAAAJ0lEQVRIx2MQRAYODEiAWQkZMIwqHFU4qnBU4ajCUYWjCkcVUkEhAIQklyN0REMMAAAAAElFTkSuQmCC",
    "gb" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAMAAABevo0zAAAAM1BMVEX///+6w9fzytGrtc3WTWM3UInxxMvIEC4BIWnAyNqqtc22wNT0ztTs7vT109n88fPO1OI8OV3ZAAABE0lEQVRIx+3XtxaDMAwF0AfBlFD//2tDDbasYnIYMvAGBpd7WJAEihJbWlezeQHVHuDN" +
        "n3EZumI5MWvrQyNt0Oe2wyppgSEHlIVB6qBrkYdCRhcoqYEcV7smWnRpoItepnE1lg2VlECWq1dQJ3lQ4A5QIzlQ5E5QJmNQ4XxQIimociHIkyFocBTkyN4He4ObwYZm6jEO5Zxh3C95IMKdfoquIyUeeE8ugdXNecAH/AX8/y+FKw5b9hLBgN/iwRWHuHzB79c5LV9k" +
        "Ny5fKtdxBVYnYXBsC9BIGJzQpGQSBie2UYmEwSmNnidhcOoowpEwOGNYiklE3MVxjpCtxSUMnIQ0uKSR2CctLnFoP0mLS/6tOMgPj+pDAxFVOjwAAAAASUVORK5CYII=",
    "hk" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1CAMAAADh9px2AAAATlBMVEXuHCX/+frwOkH0Z23+6OnuJC3vLTX////80tP/8/T94+TxREv9293/7/DzXGP6tLf7v8L1dHn5qq33lpvyUFf3jpL7xsj1fYL4nqL2hYkiMpFHAAABZ0lEQVQYGe3BR4KjMABFwa/4hITIwX3/" +
        "iw62ew5gYNELV+nr6+svGzffFt2mZKDTbUrlYHWX2PA06i4zGCDpJtFg1tFA1D0WoF8b0EWd3hw0DdDrUIrOCjXqZQcPZKuub8Akp1MceZ2H2aqDDFOIPb+S1Qk/vDlVMruix6TW+AbIUZ9z/LIzrZf6vG2NT8sPhxT0sYXD3MIY2rZXSS1P28DTqM+1kJYBNtncaxzG" +
        "bq28JOdWfW4EUgMU2dl2OsSBwxSkoBN6wHionRTjOkx7kZsei84KGwefEn6KTn2b6YOuCD0veVdICjVlctEldp2GeZH0yEUDPbS6rCzRPoxf1GNa2HWNyzxlutBAC1WXdLxUT+eg1gpWVwzgDTnRhAc8YoVOF4QGs4/GwKQVmFpwusAB/QR4K2t4sTotuspbUyTtPDU6" +
        "r6u8bUVPSwIeuiDOWzVpcvqvxQfdafZFt1qj7hX09fX1J/0DsgoSHhplIGIAAAAASUVORK5CYII=",
    "id" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1AgMAAACrRoTXAAAACVBMVEX/AAD/////f3/sDLJDAAAAG0lEQVQ4y2NgGAWjAC9YhQUwhGIBo4KjgnAAAA8AufGM9Lq4AAAAAElFTkSuQmCC",
    "ie" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoBAMAAACbTmAyAAAAD1BMVEUWm2L/iD7///9jvJb/r33nPMM8AAAAI0lEQVQ4y2NgQAZGSkhARRAZMIwqHFU4qnBU4ajCUYWkKwQAMLBvuQLjteUAAAAASUVORK5CYII=",
    "il" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA6BAMAAADVUMOiAAAAKlBMVEUAOLh/m9v////Azu4/ackXSb5tjdfR2/MlVcL4+f6uwOnr7/oHPbqXruPdtE6WAAAAvklEQVRIx2NQIhIwDAWFgkQChlFAHUB0gFMS19qbiFSolkSkwgJ2IhU6sBCnUIs1YBFRCqfyXogkqFDd" +
        "2Ng4IdiUDUgV4VWoiIgJIbwKNRtCfDhcXBqOuHJMwu/GBdEGp5WU9jBv5SLgGRW2BqCdihwJTgQUqjOA7NQM4CkiFDwJYDsXsClRS6E6AytxVhPtmQWR4OBhJxQ8RAc40VFIdKIgOplBEu6BRdTNCsRnLqKzK9EFwGitMHJqhcGmEAAQqucejHoR0gAAAABJRU5ErkJg" +
        "gg==",
    "in" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1CAMAAADh9px2AAAAP1BMVEX///8Eajj/aCBDj2r/jljo6PUOCpDa2u60s92IhslfXLbQz+rEw+RubL2mpdf39/w7OaZ/fcQkIZpST7CVk8+BV7XQAAAA3klEQVRYw+3UyW0EMQxE0bbHxZ3a84/Vh05gAOmoH8ADoYXP7+Ge" +
        "C17wghe84Av+He75JpQ+Zy94DhWDmlmjEWc8pc5ABXfSE15pUhGMAKSVfQ+kzEUkQhxK++fYJ1iKZq4Sjtm3wRYVmlN1pqLG3PUqMcvKJMpcwkz7TwYuSyeR6RLH8O0JnWVljpG5hJ3q7ohDKnSaqpmiyti+FGtwKWqmJZybbYNOnb2ESIijkx/4KcMrgjkAp3Li7xl1" +
        "BgDuZGe2A7d32zQ+tb8eXmbrS+5zuOfncBe84AUveMG3f5ZgHCG26UDJAAAAAElFTkSuQmCC",
    "is" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA6BAMAAADVUMOiAAAAIVBMVEUCUpz////cHjX2xsyBqc3xpa6autg0dK/+/v/N3evsg5AqjiRgAAAAU0lEQVRIx2NgQIBEUSUlJUFxBoJgVOGowlGF1FToggATwQrFXLACBkEkAFaIHUgQr9AYCVgBFRrjAAxKRILhpZDo4KF+" +
        "zBCdKEYz16jCUYUDrBAAtBB7r1gBBmMAAAAASUVORK5CYII=",
    "it" to
        "iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1BAMAAAAkBnF3AAAAD1BMVEXOKzcAkkb///9VtoPecHj7ZEZ0AAAAJklEQVRIx2MQRAZGSkhAhQEFjCocVTiqcFThqMJRhaMKRxVSQSEA6aGUCJuKIGMAAAAASUVORK5CYII=",
)
